---
#Provision some instances:
- name: Provision instances in AWS
  hosts: localhost
  connection: local
  gather_facts: False

# load AWS variables from group_vars file
  vars_files:
  - ../group_vars/all

  tasks:
  - name: Create Load Balancer Security Group
    ec2_group:
      name: load_balancers
      description: "Load Balancer Security Group"
      region: "{{ ec2_region }}"
      access_key: "{{ ec2_access_key }}"
      secret_key: "{{ ec2_secret_key }}"
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0

  - name: Launch load balancing instance
    ec2:
     access_key: "{{ ec2_access_key }}"
     secret_key: "{{ ec2_secret_key }}"
     keypair: "{{ ec2_keypair }}"
     group: ['default', 'load_balancers']
     type: "{{ ec2_instance_type }}"
     image: "{{ ec2_image }}"
     region: "{{ ec2_region }}"
     instance_tags: "{'Name':'loadbalancer', 'type':'{{ ec2_instance_type }}', 'group':'load_balancers'}"
     count: "1"
     wait: true
    register: ec2

  - name: Create Web Server Security Group
    ec2_group:
      name: web_servers
      description: "Web Servers Security Group"
      region: "{{ ec2_region }}"
      access_key: "{{ ec2_access_key }}"
      secret_key: "{{ ec2_secret_key }}"
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          group_name: load_balancers
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          group_name: load_balancers
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0

  - name: Launch webserver instances
    ec2:
     access_key: "{{ ec2_access_key }}"
     secret_key: "{{ ec2_secret_key }}"
     keypair: "{{ ec2_keypair }}"
     group: ['default', 'web_servers']
     type: "{{ ec2_instance_type }}"
     image: "{{ ec2_image }}"
     region: "{{ ec2_region }}"
     instance_tags: "{'Name':'webserver', 'type':'{{ ec2_instance_type }}', 'group':'web_servers'}"
     count: 2
    register: ec2

  - name: Wait for SSH to come up
    wait_for: 
      host: "{{ item.public_dns_name }}"
      port: 22 
      delay: 60 
      timeout: 320 
      state: started
    with_items: "{{ ec2.instances }}"